cargo-features = ["profile-rustflags"]

[package]
name = "host_test"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8"

[profile.dev]
rustflags = ["-Z", "export-executable-symbols"]